/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huangzb_demo_PHash */

#ifndef _Included_com_huangzb_demo_PHash
#define _Included_com_huangzb_demo_PHash
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_huangzb_demo_PHash
     * Method:    PHashMatch
     * Signature: (Ljava/lang/String;)Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_com_huangzb_demo_PHash_PHashMatch
    (JNIEnv*, jobject, jstring);

    /*
     * Class:     com_huangzb_demo_PHash
     * Method:    PHashMatchMore
     * Signature: (Lcom/huangzb/demo/pojo/pic;Ljava/util/List;)Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_com_huangzb_demo_PHash_PHashMatchMore
    (JNIEnv*, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
